services:
  server:
    build:
      context: ./server
    environment:
      - APP_DEBUG=true
      - APP_FRONTEND_URL=http://127.0.0.1:5173
      - APP_CALLBACK_URL=http://127.0.0.1:8080/auth/callback

  queue:
    build:
      context: ./queue
    environment:
      - APP_DEBUG=true
      - APP_FRONTEND_URL=http://127.0.0.1:5173

  grafana:
    environment:
      - GF_SERVER_ROOT_URL=http://localhost:3000
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

  prometheus:
    ports:
      - 127.0.0.1:9090:9090

  postgres:
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin

  redis:
    ports:
      - 127.0.0.1:6379:6379
    environment:
      - REDIS_USER=redis
      - REDIS_PASSWORD=admin
      - REDIS_KEY=O6tCucr4cOTFMe9FevF1xvu934s+JytZVqtc/F6T8L0= # not used in prod ^v^
