services:
  server:
    build:
      context: ./server

  queue:
    build:
      context: ./queue

  grafana:
    environment:
      - GF_SERVER_ROOT_URL=http://localhost:3000

  prometheus:
    ports:
      - 127.0.0.1:9090:9090

  db:
    ports:
      - 127.0.0.1:5432:5432

  redis:
    ports:
      - 127.0.0.1:6379:6379
