services:
    postgres:
        image: postgres:alpine
        container_name: overplayed-postgres
        restart: unless-stopped
        # networks:
        #     - backend
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=${POSTGRES__PASSWORD}
        # TODO: setup healthchecks

    redis:
        image: redis:alpine
        container_name: overplayed-redis
        restart: unless-stopped
        command: redis-server --requirepass ${REDIS__PASSWORD}
        volumes:
            - redis_data:/data
        networks:
            - backend # isolate communication to server only
        healthcheck:
            test: ["CMD", "redis-cli", "-a", "${REDIS__PASSWORD}", "ping"]
            interval: 10s
            timeout: 5s
            retries: 5
        ports:
            - 6379:6379

    server:
        build:
            context: server
            dockerfile: Dockerfile
        container_name: overplayed-server
        restart: unless-stopped
        ports:
            - 8080:8080
        environment:
            - SPOTIFY__CLIENT_ID
            - SPOTIFY__CLIENT_SECRET
            - REDIS__PASSWORD
            - REDIS__ENCRYPTION_KEY
        env_file:
            - .env
        networks:
            - public
            - backend
        depends_on:
            redis:
                condition: service_healthy
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080/"]
            interval: 10s
            timeout: 5s
            retries: 5

networks:
    public:
    backend:
        internal: true

volumes:
    redis_data:
