"""users

Revision ID: 65f67599511f
Revises: 8a0c9cdcd9ab
Create Date: 2026-06-14 22:08:26.389405

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "65f67599511f"
down_revision: Union[str, Sequence[str], None] = "8a0c9cdcd9ab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("spotify_url", sa.String(length=255), nullable=False),
        sa.Column("picture_url", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_foreign_key(
        "fk_swipe_sessions_user_id_users",
        "swipe_sessions",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_swipe_sessions_user_id_users", "swipe_sessions", type_="foreignkey"
    )
    op.drop_table("users")
    # ### end Alembic commands ###
