"""initial schema

Revision ID: 8a0c9cdcd9ab
Revises: 
Create Date: 2026-06-14 20:32:54.472009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a0c9cdcd9ab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('swipe_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('playlist_id', sa.String(length=255), nullable=False),
    sa.Column('snapshot_id', sa.String(length=255), nullable=False),
    sa.Column('total_tracks', sa.Integer(), nullable=False),
    sa.Column('tracks_swiped', sa.Integer(), nullable=False),
    sa.Column('tracks_cut', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_id')
    )
    op.create_index(op.f('ix_swipe_sessions_user_id'), 'swipe_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_swipe_sessions_user_id'), table_name='swipe_sessions')
    op.drop_table('swipe_sessions')
    # ### end Alembic commands ###
