@baseUrl = http://127.0.0.1:8000

### Get Queue Details
GET {{baseUrl}}/queue
Content-Type: application/json


### Get a User's Status
GET {{baseUrl}}/queue/manny@example.com
Content-Type: application/json


### Queue a User
POST {{baseUrl}}/queue
Content-Type: application/json

{
  "name": "Manny Lee",
  "email": "manny@example.com"
}

