@baseUrl = http://127.0.0.1:8000

### Get Queue Details
GET {{baseUrl}}/queue
Content-Type: application/json


### Queue a User
POST {{baseUrl}}/queue
Content-Type: application/json

{
  "name": "Ben Lee",
  "email": "ben@example.com"
}

