apiVersion: 1

# forces updates
deleteDatasources:
  - name: Prometheus
    orgId: 1

# delete datasources no longer included in a provisioning file
prune: true

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    isDefault: true
